### ISSUE TITLE
feature request - migration to akka 2.4.2 

### ISSUE THREAD

**Issue by pspiegel** [scalaspring/akka-spring-boot#1]
hi lancearlaus
question: would it be possible to migrate the code to akka v2.4.2, the current stable release (in combi with spring boot v1.3.3) and create a new version of it (for java and maven)? we need the 2.4.x java part to go with the new distributed data option.

and i'm definitely not the skilled scala developer to get that done by the way.. 
thx for your answer, pspiegel

**Comment by lancearlaus** [comment]
Yes, not a problem. I've been meaning to do that for a while, so thanks for the prompt. I may not get to it until this weekend, though. Is there an urgent need?

**Comment by pspiegel** [comment]
It's not that urgent.
Thus, next week would be fine. Thx.

**Comment by pspiegel** [comment]
?

**Comment by lancearlaus** [comment]
I made the necessary changes this past weekend to upgrade to 2.4.2.

However, I noticed and issue while unbinding in  Akka HTTP. I know the Akka team made significant changes in their shutdown code. I want to bottom out that issue before packaging a release.
Expected this weekend as I get another time slice to address.

**Comment by lancearlaus** [comment]
Published a new release (0.3.1) that incorporates the latest Akka and Spring release versions.
Minor internal implementation changes required, but no external interface changes.
Added the ability to adjust the lifecycle phase of the actor system lifecycle bean.

**Comment by pspiegel** [comment]
Great, thx alot for your effort.

Are u publishing the new artifacts to the central mavenrepo (http://mvnrepository.com/artifact/com.github.scalaspring) or who's doing that?

**Comment by lancearlaus** [comment]
Already done as part of the release.
You should be able to pull down the new version if you update your dependency to 0.3.1.
The repo search index usually takes a little time to catch up and reflect the new version.
